In [1]:
##Machine Learning KNN assignments

In [134]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [109]:
file="/Users/bibekprasad/Documents/Data science webex/haberman.data"

In [110]:
col_name=["Age of patient at TOA","Patient's year of operation ","Number of PAN detected","Survival status"]

In [111]:
cancer=pd.read_table(file,sep=",",names=col_name)

In [112]:
cancer

Age of patient at TOA  Patient's year of operation   \
0                       30                            64   
1                       30                            62   
2                       30                            65   
3                       31                            59   
4                       31                            65   
..                     ...                           ...   
301                     75                            62   
302                     76                            67   
303                     77                            65   
304                     78                            65   
305                     83                            58   

     Number of PAN detected  Survival status  
0                         1                1  
1                         3                1  
2                         0                1  
3                         2                1  
4                         4                1  
..                      ...              ...  
301                       1                1  
302                       0                1  
303                       3                1  
304                       1                2  
305                       2                2  

[306 rows x 4 columns]

In [113]:
##independent variable--Age of patient at TOA	Patient's year of operation	Number of PAN detected

##target varibale--Survival status

In [114]:
pd.isna(cancer)

Age of patient at TOA  Patient's year of operation   \
0                    False                         False   
1                    False                         False   
2                    False                         False   
3                    False                         False   
4                    False                         False   
..                     ...                           ...   
301                  False                         False   
302                  False                         False   
303                  False                         False   
304                  False                         False   
305                  False                         False   

     Number of PAN detected  Survival status  
0                     False            False  
1                     False            False  
2                     False            False  
3                     False            False  
4                     False            False  
..                      ...              ...  
301                   False            False  
302                   False            False  
303                   False            False  
304                   False            False  
305                   False            False  

[306 rows x 4 columns]

In [115]:
cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 4 columns):
Age of patient at TOA           306 non-null int64
Patient's year of operation     306 non-null int64
Number of PAN detected          306 non-null int64
Survival status                 306 non-null int64
dtypes: int64(4)
memory usage: 9.7 KB


In [116]:
cancer["Patient's year of operation "].value_counts()


58    36
64    31
63    30
66    28
65    28
60    28
59    27
61    26
67    25
62    23
68    13
69    11
Name: Patient's year of operation , dtype: int64

In [117]:
cancer["Number of PAN detected"].value_counts()

0     136
1      41
2      20
3      20
4      13
6       7
7       7
8       7
5       6
9       6
13      5
14      4
11      4
10      3
15      3
19      3
22      3
23      3
12      2
20      2
46      1
16      1
17      1
18      1
21      1
24      1
25      1
28      1
30      1
35      1
52      1
Name: Number of PAN detected, dtype: int64

In [118]:
cancer["Age of patient at TOA"].value_counts()

52    14
54    13
50    12
47    11
53    11
43    11
57    11
55    10
65    10
49    10
38    10
41    10
61     9
45     9
42     9
63     8
59     8
62     7
44     7
58     7
56     7
46     7
70     7
34     7
48     7
37     6
67     6
60     6
51     6
39     6
66     5
64     5
72     4
69     4
40     3
30     3
68     2
73     2
74     2
36     2
35     2
33     2
31     2
78     1
71     1
75     1
76     1
77     1
83     1
Name: Age of patient at TOA, dtype: int64

In [119]:

cancer["Survival status"].value_counts()

1    225
2     81
Name: Survival status, dtype: int64

In [120]:
x=np.array(cancer.drop(["Survival status"],1))

In [121]:
x

array([[30, 64,  1],
       [30, 62,  3],
       [30, 65,  0],
       [31, 59,  2],
       [31, 65,  4],
       [33, 58, 10],
       [33, 60,  0],
       [34, 59,  0],
       [34, 66,  9],
       [34, 58, 30],
       [34, 60,  1],
       [34, 61, 10],
       [34, 67,  7],
       [34, 60,  0],
       [35, 64, 13],
       [35, 63,  0],
       [36, 60,  1],
       [36, 69,  0],
       [37, 60,  0],
       [37, 63,  0],
       [37, 58,  0],
       [37, 59,  6],
       [37, 60, 15],
       [37, 63,  0],
       [38, 69, 21],
       [38, 59,  2],
       [38, 60,  0],
       [38, 60,  0],
       [38, 62,  3],
       [38, 64,  1],
       [38, 66,  0],
       [38, 66, 11],
       [38, 60,  1],
       [38, 67,  5],
       [39, 66,  0],
       [39, 63,  0],
       [39, 67,  0],
       [39, 58,  0],
       [39, 59,  2],
       [39, 63,  4],
       [40, 58,  2],
       [40, 58,  0],
       [40, 65,  0],
       [41, 60, 23],
       [41, 64,  0],
       [41, 67,  0],
       [41, 58,  0],
       [41, 5

In [122]:
y=np.array(cancer["Survival status"])

In [123]:
y

array([1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2,
       2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1,

In [124]:
from sklearn.model_selection import train_test_split

In [125]:
##Test and train data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=60)

In [126]:
x_train

array([[59, 63,  0],
       [39, 63,  0],
       [55, 69,  3],
       [76, 67,  0],
       [65, 66, 15],
       [68, 68,  0],
       [66, 58,  1],
       [31, 59,  2],
       [56, 66,  3],
       [43, 65,  0],
       [42, 69,  1],
       [43, 58, 52],
       [30, 64,  1],
       [50, 64,  0],
       [42, 61,  4],
       [50, 63, 13],
       [66, 58,  0],
       [47, 66,  0],
       [57, 64,  0],
       [40, 58,  2],
       [50, 64,  0],
       [53, 65,  1],
       [66, 68,  0],
       [56, 60,  0],
       [52, 62,  0],
       [64, 61,  0],
       [54, 67, 46],
       [64, 66,  0],
       [31, 65,  4],
       [52, 63,  4],
       [48, 64,  0],
       [33, 58, 10],
       [42, 65,  0],
       [41, 58,  0],
       [51, 64,  7],
       [54, 68,  7],
       [67, 66,  0],
       [63, 60,  1],
       [43, 60,  0],
       [57, 69,  0],
       [59, 67,  3],
       [50, 59,  0],
       [42, 59,  2],
       [39, 58,  0],
       [41, 65,  0],
       [35, 64, 13],
       [65, 64,  0],
       [60, 5

In [127]:
y_train

array([1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1,
       2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2,
       1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1,
       2, 1])

In [151]:
knn=KNeighborsClassifier()  #model selected


In [152]:
knn.fit(x_train,y_train)  ## model trained with train data

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [153]:
y_pred=knn.predict(x_test)

In [154]:
y_pred

array([1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1])

In [155]:
y_test

array([1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1])

In [156]:
acc=knn.score(x_test,y_test)

In [157]:
acc

0.6774193548387096

In [158]:
knn.score(x_test,y_test)

0.6774193548387096